config/routes.rb
Rails.application.routes.draw do

      root 'home#index'

      devise_for :users, controllers: {
        sessions: 'users/sessions'
      }

      resources :neighborhoods, only: :index do
        resources :bars
      end

      get '/neighborhoods/all', to: 'neighborhoods#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bar.rb
class Bar < ApplicationRecord
  belongs_to :neighborhood

  validates :name, presence: true
  validates :specialty_drink, presence: true
end

app/models/model.rb
class Model < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/neighborhood.rb
class Neighborhood < ApplicationRecord
  has_many :bars
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  ## note - authenticate user after protect_from_forgery
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name])
  end
end

app/controllers/bars_controller.rb
class BarsController < ApplicationController
  before_action :find_neighborhood
  before_action :find_bar, except: [:index, :new, :create]

  def index
    @bars = @neighborhood.bars
  end

  def show

  end

  def create
    @bar = @neighborhood.bars.new(bar_params)

    if @bar.save
      if request.xhr?
        render json: @bar
      else
        redirect_to neighborhood_bar_path(@neighborhood, @bar)
      end
    else
      @errors = @bar.errors.full_messages
      render 'new'
    end
  end

  def new
    @bar = Bar.new

    if request.xhr?
      render partial: 'form'
    end
  end

  def edit
  end

  def update
    if @bar.update(bar_params)
      redirect_to neighborhood_bar_path(@neighborhood, @bar)
    else
      @errors = @bar.errors.full_messages
      render 'edit'
    end
  end

  def destroy
    @bar.destroy
    redirect_to neighborhood_bars_path(@neighborhood)
  end


  private

  def find_neighborhood
    @neighborhood = Neighborhood.find(params[:neighborhood_id])
  end

  def find_bar
    @bar = Bar.find(params[:id])
  end

  def bar_params
    params.require(:bar).permit(:name, :specialty_drink, :cash_only)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/neighborhoods_controller.rb
class NeighborhoodsController < ApplicationController
  def index
    @neighborhoods = Neighborhood.all
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bars_helper.rb
module BarsHelper
end

app/helpers/neighborhoods_helper.rb
module NeighborhoodsHelper
end

app/views/bars/_form.html.erb
<%= form_for [@neighborhood, @bar], remote: true do |f| %>
  <div id="form-part">
    <%= f.label :name %>
    <%= f.text_field :name, placeholder: "Name" %>
  </div>
  <div id="form-part">
    <%= f.label :specialty_drink %>
    <%= f.text_field :specialty_drink, placeholder: "Specialty drink" %>
  </div>
  <div id="form-part">
    <%= f.label :cash_only %>
    <%= f.select :cash_only, options_for_select([["true", true], ["false", false]])%>
  </div>
    <%= f.submit %>
<% end %>

app/views/bars/create.html.erb
<h1>Bars#create</h1>
<p>Find me in app/views/bars/create.html.erb</p>

app/views/bars/destroy.html.erb
<h1>Bars#destroy</h1>
<p>Find me in app/views/bars/destroy.html.erb</p>

app/views/bars/edit.html.erb
<h1>Bars#edit</h1>
<p>Find me in app/views/bars/edit.html.erb</p>

<% if @errors %>
  <ul>
    <% @errors.each do |error| %>
    <li><%= error %></li>
    <% end %>
  </ul>
<% end %>



<%= form_for [@neighborhood, @bar] do |f| %>
  <div id="form-part">
    <%= f.label :name %>
    <%= f.text_field :name%>
  </div>
  <div id="form-part">
    <%= f.label :specialty_drink %>
    <%= f.text_field :specialty_drink%>
  </div>
  <div id="form-part">
    <%= f.label :cash_only %>
    <%= f.select :cash_only, options_for_select([["true", true], ["false", false]])%>
  </div>
    <%= f.submit %>
<% end %>

app/views/bars/index.html.erb
<h1>Bars#index</h1>
<p>Find me in app/views/bars/index.html.erb</p>

<h1><%= @neighborhood.name %></h1>
<%= link_to 'Add a new bar!', new_neighborhood_bar_path(@neighborhood), remote: true, id: "add-bar-link" %>

<div id="form-holder">

</div>

<ul>
  <% @bars.each do |bar| %>
    <li><%= link_to bar.name, neighborhood_bar_path(@neighborhood, bar) %></li>
  <% end %>
</ul>

app/views/bars/new.html.erb
<h1>Bars#new</h1>
<p>Find me in app/views/bars/new.html.erb</p>

<% if @errors %>
  <ul>
    <% @errors.each do |error| %>
    <li><%= error %></li>
    <% end %>
  </ul>
<% end %>



<%= form_for [@neighborhood, @bar] do |f| %>
  <div id="form-part">
    <%= f.label :name %>
    <%= f.text_field :name, placeholder: "Name" %>
  </div>
  <div id="form-part">
    <%= f.label :specialty_drink %>
    <%= f.text_field :specialty_drink, placeholder: "Specialty drink" %>
  </div>
  <div id="form-part">
    <%= f.label :cash_only %>
    <%= f.select :cash_only, options_for_select([["true", true], ["false", false]])%>
  </div>
    <%= f.submit %>
<% end %>

app/views/bars/show.html.erb
<h1><%= @bar.name %></h1>
<p>Neighborhood:</p>
  <%= @neighborhood.name %>

<p>Specialty Drink:</p>
  <%= @bar.specialty_drink %>

<p>Cash only?</p>
  <%= @bar.cash_only %>

<%= link_to 'Edit bar info', edit_neighborhood_bar_path(@neighborhood, @bar) %>

<%= link_to 'Delete bar', neighborhood_bar_path(@neighborhood, @bar), method: 'delete' %>

app/views/bars/update.html.erb
<h1>Bars#update</h1>
<p>Find me in app/views/bars/update.html.erb</p>

app/views/home/index.html.erb
<h1>Home Page</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Barhop</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/neighborhoods/index.html.erb
<h1>neighborhoods#index</h1>
<ul>
<% @neighborhoods.each do |neighborhood| %>
  <li><%= link_to neighborhood.name, neighborhood_bars_path(neighborhood) %></li>
<% end %>
</ul>